[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "random", "--transition-step", "60", "--transition-fps", "120"]
set = true

[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = '~/.config/hypr/matugen-colors.conf'
post_hook = 'hyprctl reload'
